#pragma once

#define BNS_MOUSE_BUTTON_1 0
#define BNS_MOUSE_BUTTON_2 1
#define BNS_MOUSE_BUTTON_3 2
#define BNS_MOUSE_BUTTON_4 3
#define BNS_MOUSE_BUTTON_5 4
#define BNS_MOUSE_BUTTON_6 5
#define BNS_MOUSE_BUTTON_7 6
#define BNS_MOUSE_BUTTON_8 7
#define BNS_MOUSE_BUTTON_LAST BNS_MOUSE_BUTTON_8
#define BNS_MOUSE_BUTTON_LEFT BNS_MOUSE_BUTTON_1
#define BNS_MOUSE_BUTTON_RIGHT BNS_MOUSE_BUTTON_2
#define BNS_MOUSE_BUTTON_MIDDLE BNS_MOUSE_BUTTON_3